services:
  app:
    image: ruzinovrun143/docker-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    platform: linux/amd64
    command: make test
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./app:/app
    # volumes:
    #  - ".env.example:/.env"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER:     ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB:       ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
