FROM node:20.12.2
WORKDIR /app

RUN ls -la .

COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci

COPY app/. .

EXPOSE 8080

CMD ["make prepare-env", "make start", ]
