services:
  app:
    image: ruzinovrun143/docker-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    platform: linux/amd64
    volumes:
      - ./app:/app
    command: make test
